### ISSUE TITLE
Отсутствие контраста схемы этажей в темной тем

### ISSUE THREAD

**Issue by dyakovri** [profcomff/services-webapp#12]

**Comment by netsvetoch** [comment]
Кажется, это не наша проблема. В некоторых смартфонах (напр., Xiaomi) есть форсированная темная тема, она красит принудительно

**Comment by dyakovri** [comment]
Есть медиа запрос `prefers-color-scheme`, предлагаю заюзать его и установить background color фону и filter (или color?) картинкам

**Comment by netsvetoch** [comment]
по факту это большая задача по созданию темной темы в приложении. Мне кажется, сейчас нам не до нее

**Comment by netsvetoch** [comment]
поправили html файл на сервере, теперь в карте присутствует темная тема
